defaults:
  - base

target:
  _target_: src.models.resnet50_OOD.pretrained_model
  out_features: "${dataset.datasets.n_classes}"

out_features: ${dataset.datasets.n_classes}

description: Resnet50 pré-entrainé avec ${.target.out_features} classes en sortie
hyperparameters:
  model: resnet50_pretrained
