datasets:
  data_dir: ${paths.data_dir}
  name: ???
  hyperparameters:
    dataset: ${..name}

loaders:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 16
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 512
    shuffle: False
    num_workers: 16
    drop_last: False
    pin_memory: False
