_target_: src.datamodules.imagenet64.Imagenet64DataModule

defaults:
  - default
  - default_hierarchy


datasets:
  name: imagenet64_unscaled
  path: ${paths.imagenet64_dir}
  n_classes: 1000
  hierarchy_filename: imagenet64_tree.txt
  synset_filename: none.txt

paths:
  hierarchy_dir: data/hierarchy/

transforms:
  train:
    _target_: torchvision.transforms.Compose
    _args_:
      - - _target_: torchvision.transforms.ToTensor
        - ${attr:"src.datamodules.utils.ToRGB"}
        - _target_: torchvision.transforms.Resize
          size: [224, 224]


  valid:
    _target_: torchvision.transforms.Compose
    _args_:
      - - _target_: torchvision.transforms.ToTensor
        - ${attr:"src.datamodules.utils.ToRGB"}
        - _target_: torchvision.transforms.Resize
          size: [224, 224]



loaders:
  train:
    batch_size: 128
    shuffle: True
    num_workers: 16
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 128
    shuffle: False
    num_workers: 16
    drop_last: False
    pin_memory: False
