_target_: src.datamodules.imagenet64_subset.Imagenet64SubsetDataModule

defaults:
  - default
  - default_hierarchy


datasets:
  name: imagenet64_autoaugment_r${.reduction_factor}_s${.seed}
  path: ${paths.imagenet64_dir}
  n_classes: 1000
  hierarchy_filename: imagenet64_tree_wordnet.txt
  synset_filename: none.txt
  reduction_factor: 32
  seed: 42

paths:
  hierarchy_dir: data/hierarchy/

transforms:
  train:
    _target_: torchvision.transforms.Compose
    _args_:
      - - _target_: torchvision.transforms.Resize
          size: [64, 64]
        - _target_: torchvision.transforms.Resize
          size: [224, 224]
        - _target_: torchvision.transforms.AutoAugment
          policy: ${attr:"torchvision.transforms.AutoAugmentPolicy.IMAGENET"}
        - _target_: torchvision.transforms.ToTensor
        - ${attr:"src.datamodules.utils.ToRGB"}
        - _target_: torchvision.transforms.Normalize
          _args_:
            - [0.40790028480201174, 0.45752540989626844, 0.48114099039657426]
            - [0.27051001282083936, 0.2557205199865213, 0.2629382754293579]

  valid:
    _target_: torchvision.transforms.Compose
    _args_:
      - - _target_: torchvision.transforms.Resize
          size: [64, 64]
        - _target_: torchvision.transforms.Resize
          size: [224, 224] 
        - _target_: torchvision.transforms.ToTensor
        - ${attr:"src.datamodules.utils.ToRGB"}
        - _target_: torchvision.transforms.Normalize
          _args_:
            - [0.40790028480201174, 0.45752540989626844, 0.48114099039657426]
            - [0.27051001282083936, 0.2557205199865213, 0.2629382754293579]

loaders:
  train:
    batch_size: 128
    shuffle: True
    num_workers: 16
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 128
    shuffle: False
    num_workers: 16
    drop_last: False
    pin_memory: False
