_target_: src.datamodules.tinyimagenet.TinyImagenetDataModule

defaults:
  - default
  - default_hierarchy
  - default_huggingface
  - _self_
  - optional foo@_here_: ../tinyimagenet_${machine_name:} # Per-machine override of configuration below

datasets:
  name: TinyImagenet
  path: zh-plus/tiny-imagenet
  n_classes: 200
  hierarchy_filename: tinyimagenet_hierarchy.json
  synset_filename: tinyimagenet_synset.txt

transforms:
  train:
    _target_: torchvision.transforms.v2.Compose
    _args_:
      - - _target_: torchvision.transforms.v2.ToImage
        - ${attr:"src.datamodules.utils.ToRGB"} # Some images are grayscale
        - _target_: torchvision.transforms.v2.ToDtype
          _args_:
            - ${attr:"torch.float32"}
          scale: True
        - _target_: torchvision.transforms.v2.Normalize
          mean: [0.48023462867919975, 0.44807240576811214, 0.3975059588114215]
          std: [0.27643921134213034, 0.2688699788209063, 0.2815982659992735]

  valid:
    _target_: torchvision.transforms.v2.Compose
    _args_:
      - - _target_: torchvision.transforms.v2.ToImage
        - ${attr:"src.datamodules.utils.ToRGB"}
        - _target_: torchvision.transforms.v2.ToDtype
          _args_:
            - ${attr:"torch.float32"}
          scale: True
        - _target_: torchvision.transforms.v2.Normalize
          mean: [0.48023462867919975, 0.44807240576811214, 0.3975059588114215]
          std: [0.27643921134213034, 0.2688699788209063, 0.2815982659992735]
