# @package _global_

trainer:
  target:
    max_epochs: 1
    accelerator: cpu # debuggers don't like gpus
    devices: 1 # debuggers don't like multiprocessing
    detect_anomaly: true # raise exception if NaN or +/-inf is detected in any tensor

dataset:
  loaders:
    train:
      num_workers: 0
      pin_memory: False
    valid:
      num_workers: 0
      pin_memory: False
    test:
      num_workers: 0
      pin_memory: False
